#!/bin/bash

# This script performs a backup of the specified
# folder to the specified backup location

FROM_DIR=$1
TO_DIR=$2

cd ${TO_DIR}

### Make backups writable
chmod u+w daily.*

### Delete the oldest daily backup, if it exists
#
if [ -d daily.3 ] ; then
rm -rf daily.3 ;
fi

### Shift the middle snapshots(s) back by one, if they exist
if [ -d daily.2 ] ; then
mv daily.2 daily.3 ;
fi
if [ -d daily.1 ] ; then
mv daily.1 daily.2 ;
fi
if [ -d daily.0 ] ; then
mv daily.0 daily.1 ;
fi

### Make backup
#
# This method creates hard-links to the previous backup for unchanged
# files, saving considerable space.
#
rsync -a --delete --link-dest=daily.1 ${FROM_DIR}/ daily.0/

### Update the mtime of daily.0 to reflect the snapshot time
#
touch daily.0 ;

### Make backups write-protected
chmod a-w daily.*

cd -