#!/bin/bash

# This script rotates the oldest weekly backup
# to monthly backup.

cd $1

### Make backups writable
if [ -d monthly.0 ] ; then
chmod u+w monthly.*
fi

### Delete the oldest monthly backup, if it exists
#
if [ -d monthly.3 ] ; then
chmod -R u+w monthly.3
rm -rf monthly.3
fi

### Shift the middle snapshots(s) back by one, if they exist
if [ -d monthly.2 ] ; then
mv monthly.2 monthly.3 ;
fi
if [ -d monthly.1 ] ; then
mv monthly.1 monthly.2 ;
fi
if [ -d monthly.0 ] ; then
mv monthly.0 monthly.1 ;
fi

### Hard link oldest weekly backup to monthly backup
#
if [ -d weekly.3 ] ; then
cp -al weekly.3 monthly.0
fi

### Make backups write-protected
chmod a-w monthly.*

cd - > /dev/null
