#!/bin/bash

# This script rotates the oldest daily backup
# to weekly backup.

cd $1

### Make backups writable
if [ -d weekly.0 ] ; then
chmod u+w weekly.*
fi

### Delete the oldest weekly backup, if it exists
#
if [ -d weekly.3 ] ; then
rm -rf weekly.3
fi

### Shift the middle snapshots(s) back by one, if they exist
if [ -d weekly.2 ] ; then
mv weekly.2 weekly.3 ;
fi
if [ -d weekly.1 ] ; then
mv weekly.1 weekly.2 ;
fi
if [ -d weekly.0 ] ; then
mv weekly.0 weekly.1 ;
fi

### Hard link oldest daily backup to weekly backup
#
if [ -d daily.3 ] ; then
cp -al daily.3 weekly.0
fi

### Make backups write-protected
chmod a-w weekly.*

cd - > /dev/null
